# Generated by Django 3.1.5 on 2021-05-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=30, verbose_name='Yazar Adı')),
                ('author_lastname', models.CharField(max_length=30, verbose_name='Yazarın Soyadı')),
            ],
        ),
        migrations.CreateModel(
            name='book_species',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Kitap Adı')),
                ('sayfa_sayisi', models.IntegerField(blank=True)),
                ('yayin_tarihi', models.DateTimeField(blank=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('book_species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book_species')),
            ],
        ),
    ]
